### ISSUE TITLE
- include should be --include

### ISSUE THREAD

**Issue by lanceplaine** [hellobrian/blogs#1]
<img width="721" alt="screen shot 2016-02-29 at 9 42 32 am" src="https://cloud.githubusercontent.com/assets/5476205/13389511/d37006ae-dec8-11e5-9ccc-9c9189663f51.png">

**Comment by hellobrian** [comment]
Thanks, will make that change pronto

**Comment by hellobrian** [comment]
Fixed [here](https://github.com/hellobrian/blogs/tree/master/watch-and-compile-your-sass-with-npm#refactor-move-scripts-into-their-own-files) and on [medium](https://medium.com/@brianhan/watch-compile-your-sass-with-npm-9ba2b878415b#.jctn2w47s) :beers: Cheers!
