### ISSUE TITLE
double space missing

### ISSUE THREAD

**Issue by ghost** [hellobrian/blogs#2]
Hi!,  thanks for the thorough and clear rundown.  I just wanted to mention a little typo:

"scripts": {
 "build-css": "node-sass --include-path scss scss/main.scsspublic/css/main.css",
 "watch-css": "nodemon -e scss -x \"npm run build-css\""
}, 

//  Should'nt this have double space between source and destination folders? //

"scripts": {
 "build-css": "node-sass --include-path scss scss/main.scss  public/css/main.css",
 "watch-css": "nodemon -e scss -x \"npm run build-css\""
},

Thanks Again for sharing!

**Comment by hellobrian** [comment]
Thanks, just fixed the spacing issue. I think it should only be one space. 
Let me know if the problem still persists. Thanks again
